name: en_super
description: A Flutter app for learning English vocabulary.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  fl_chart: ^0.67.0
  share_plus: ^10.0.0
  flutter_tts: ^4.0.2
  lottie: ^3.1.2
  path_provider: ^2.1.3
  json_annotation: ^4.9.0
  flutter_local_notifications: ^17.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.7
  hive_generator: ^2.0.1
  json_serializable: ^6.8.0
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1


flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/app_icon.png"



flutter:
  uses-material-design: true
  assets:
    - assets/app_icon.png
    - assets/animations/
    - assets/data/vocab.json
    - assets/data/stories.json
  fonts:
    - family: Vazir
      fonts:
        - asset: assets/fonts/Vazir-Regular.ttf
        - asset: assets/fonts/Vazir-Bold.ttf
          weight: 700